// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Get session ID with lazy initialization to handle module load order
function getSessionIdForClient(): string {
  const SESSION_KEY = 'restaurant_session_id';
  let sessionId = sessionStorage.getItem(SESSION_KEY);
  
  if (!sessionId) {
    const timestamp = Date.now();
    const randomPart = Math.random().toString(36).substring(2, 15);
    sessionId = `session_${timestamp}_${randomPart}`;
    sessionStorage.setItem(SESSION_KEY, sessionId);
  }
  
  return sessionId;
}

// Create a function to get client with current session headers
function createSupabaseClient(): SupabaseClient<Database> {
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        // Pass session ID for RLS policies to validate
        'x-session-id': getSessionIdForClient(),
      },
    },
  });
}

// Export supabase client
// Note: This client includes session headers for RLS policy validation
export const supabase = createSupabaseClient();
